name: generate animated snake

on:
  schedule:
    - cron: "0 0 * * *"  # run daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate animated snake (light theme)
        uses: jolaleye/github-contribution-snake@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: light
          output: dist/github-contribution-grid-snake.svg

      - name: Generate animated snake (dark theme)
        uses: jolaleye/github-contribution-snake@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: dark
          output: dist/github-contribution-grid-snake-dark.svg

      - name: Push generated snakes to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
